from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app) # Enable CORS for all routes

LANGUAGES = {
    "English": {
        "name": "Name",
        "mobile": "Mobile Number",
        "aadhaar": "Aadhaar Number",
        "doctor": "Doctor",
        "register": "Register",
        "scan_face": "Scan Face",
        "appointment": "Appointment",
        "submit": "Submit",
        "welcome_to_app": "Welcome to Smart Health",
        "app_description": "Your digital gateway to seamless healthcare.<br>Book appointments, check-in at kiosks, and manage your health easily.",
        "get_started": "Get Started",
        "choose_lang": "Choose Your Language",
        "registration_login": "Registration / Login",
        "abha_id": "ABHA ID (optional)",
        "face_scan": "Face Scan (Upload)",
        "consent_ehr": "I consent to share my EHR with authorized professionals.",
        "register_login_btn": "Register / Login",
        # New label for the button to proceed to face registration
        "face_registration_link": "Proceed to Face Registration", 
        "book_appointment": "Book Doctor Appointment",
        "department": "Department",
        "mode": "Mode",
        "date": "Date",
        "time": "Time",
        "confirm_appointment": "Confirm Appointment",
        "appointment_confirmed": "Appointment Confirmed",
        "token": "Token",
        "proceed_sync": "Proceed: Sync with Kiosk",
        "ready_to_visit_kiosk": "Ready to Visit Kiosk",
        "appointment_scheduled_msg_part1": "Your appointment is scheduled at the kiosk on",
        "appointment_scheduled_msg_part2": "Please proceed to the kiosk. Your Patient ID:",
        "done": "Done",
        "welcome_to_kiosk": "Welcome to the Kiosk",
        "your_health_reports": "Your Health Reports",
        "latest_consultation": "Latest Consultation:",
        "prescription_label": "Prescription:",
        "vitals_label": "Vitals: BP",
        "bmi_label": ", BMI",
        "download_pdf": "Download PDF",
        "kiosk_choose_lang": "Kiosk: Choose Your Language",
        "kiosk_login": "Kiosk Login",
        "face_id": "Face ID",
        "fingerprint": "Fingerprint",
        "patient_id": "Patient ID",
        "enter_patient_id": "Enter Patient ID",
        "login_btn": "Login",
        "kiosk_appointment_found": "Kiosk: Appointment Found",
        "patient_id_label": "Patient ID:",
        "confirm_proceed": "Confirm & Proceed",
        "vitals_diagnostics": "Vitals & Diagnostics",
        "auto_capture_vitals": "Auto-Capture Vitals",
        "proceed_teleconsultation": "Proceed to Teleconsultation",
        "teleconsultation": "Teleconsultation",
        "start_consultation": "Start Consultation",
        "proceed_summary": "Proceed to Summary",
        "consultation_summary": "Consultation Summary",
        "proceed_payment": "Proceed to Payment",
        "payment": "Payment",
        "consultation_fee": "Consultation Fee: ₹500",
        "confirm_payment": "Confirm Payment",
        "name_error": "Name: letters only",
        "mobile_error": "Mobile: 10 digits",
        "aadhaar_error": "Aadhaar: 12 digits",
        "fill_all_fields": "Please fill all fields.",
        "scanning_face_id": "Scanning Face ID...",
        "recognizing_face": "Recognizing face...",
        "face_recognized_success": "Face recognized for Patient ID:",
        "face_recognition_failed": "Face recognition failed:",
        "face_recognition_error": "Error connecting to face recognition service.",
        "scanning_fingerprint": "Scanning Fingerprint...",
        "invalid_patient_id": "Invalid Patient ID.",
        "measuring": "Measuring...",
        "vitals_captured": "Height: 172 cm<br>Weight: 68 kg<br>Temp: 98.6°F<br>BP: 120/80 mmHg<br>Heart Rate: 72 bpm<br>BMI: 23.0",
        "connecting": "Connecting to remote doctor...",
        "consultation_complete": "Consultation Complete. Prescription generated.",
        "summary_details": "<b>Diagnosis:</b> Hypertension<br><b>Prescription:</b> Amlodipine 5mg daily<br><b>Follow-up:</b> 1 month<br><b>Summary sent to App.</b>",
        "processing_payment": "Processing payment...",
        "payment_successful": "Payment successful! Receipt sent to app.",
        "app_header": "Smart Health App & Kiosk",
        "app_footer": "© 2025 Smart Health App & Kiosk Demo. Built with HTML, CSS & JavaScript.",
        "date_time": "Date/Time",
        "no_appointment_finger": "No active appointment found for fingerprint login.",
        "date_unavailable": "Selected date is not available. Please choose another.",
        "face_registration": "Face Registration",
        "face_register_prompt": "Please capture or upload a clear photo of your face.",
        "capture_photo": "Capture Photo",
        "upload_photo_btn": "Upload Photo",
        "register_face_btn": "Register Face",
        "back_to_registration": "Back to Registration",
        "webcam_error": "Webcam access denied or not available.",
        "photo_captured": "Photo captured. Click Register Face.",
        "no_video_stream": "No video stream available to capture photo.",
        "photo_uploaded": "Photo uploaded. Click Register Face.",
        "capture_upload_first": "Please capture or upload a photo first.",
        "register_first_error": "Please register your basic details first.",
        "registering_face": "Registering face...",
        "face_registered_msg": "Face successfully registered!",
        "face_registration_failed": "Face registration failed:",
        "network_error_face_reg": "Network error or server unavailable during face registration.",
        "scanning_face_sim": "Scanning face...",
        "face_not_recognized_kiosk": "Face not recognized. Please register in the app first or try Patient ID.",
        "network_error_face_rec": "Network error or server unavailable during face recognition."
    },
    "Hindi": {
        "name": "नाम",
        "mobile": "मोबाइल नंबर",
        "aadhaar": "आधार नंबर",
        "doctor": "डॉक्टर",
        "register": "पंजीकरण",
        "scan_face": "चेहरा स्कैन करें",
        "appointment": "नियुक्ति",
        "submit": "जमा करें",
        "welcome_to_app": "स्मार्ट हेल्थ में आपका स्वागत है",
        "app_description": "स्वास्थ्य सेवा के लिए आपका डिजिटल गेटवे।<br>नियुक्ति बुक करें, कियोस्क पर चेक-इन करें और आसानी से अपने स्वास्थ्य का प्रबंधन करें।",
        "get_started": "शुरू हो जाओ",
        "choose_lang": "अपनी भाषा चुनें",
        "registration_login": "पंजीकरण / लॉगिन",
        "abha_id": "ABHA ID (वैकल्पिक)",
        "face_scan": "चेहरा स्कैन करें (अपलोड)",
        "consent_ehr": "मैं अधिकृत पेशेवरों के साथ अपना EHR साझा करने के लिए सहमत हूं।",
        "register_login_btn": "पंजीकरण / लॉगिन",
        "face_registration_link": "चेहरा पंजीकरण के लिए आगे बढ़ें",
        "book_appointment": "डॉक्टर अपॉइंटमेंट बुक करें",
        "department": "विभाग",
        "mode": "मोड",
        "date": "दिनांक",
        "time": "समय",
        "confirm_appointment": "अपॉइंटमेंट की पुष्टि करें",
        "appointment_confirmed": "अपॉइंटमेंट की पुष्टि हुई",
        "token": "टोकन",
        "proceed_sync": "आगे बढ़ें: कियोस्क के साथ सिंक करें",
        "ready_to_visit_kiosk": "कियोस्क पर जाने के लिए तैयार",
        "appointment_scheduled_msg_part1": "आपका अपॉइंटमेंट कियोस्क पर निर्धारित है",
        "appointment_scheduled_msg_part2": "कृपया कियोस्क पर जाएं। आपका रोगी आईडी:",
        "done": "हो गया",
        "welcome_to_kiosk": "कियोस्क में आपका स्वागत है",
        "your_health_reports": "आपकी स्वास्थ्य रिपोर्ट",
        "latest_consultation": "नवीनतम परामर्श:",
        "prescription_label": "पर्चे:",
        "vitals_label": "महत्वपूर्ण: बीपी",
        "bmi_label": ", बीएमआई",
        "download_pdf": "पीडीएफ डाउनलोड करें",
        "kiosk_choose_lang": "कियोस्क: अपनी भाषा चुनें",
        "kiosk_login": "कियोस्क लॉगिन",
        "face_id": "फेस आईडी",
        "fingerprint": "फिंगरप्रिंट",
        "patient_id": "रोगी आईडी",
        "enter_patient_id": "रोगी आईडी दर्ज करें",
        "login_btn": "लॉग इन करें",
        "kiosk_appointment_found": "कियोस्क: अपॉइंटमेंट मिला",
        "patient_id_label": "रोगी आईडी:",
        "confirm_proceed": "पुष्टि करें और आगे बढ़ें",
        "vitals_diagnostics": "महत्वपूर्ण और निदान",
        "auto_capture_vitals": "स्वचालित रूप से महत्वपूर्ण कैप्चर करें",
        "proceed_teleconsultation": "टेलीकंसल्टेशन के लिए आगे बढ़ें",
        "teleconsultation": "टेलीकंसल्टेशन",
        "start_consultation": "परामर्श शुरू करें",
        "proceed_summary": "सारांश के लिए आगे बढ़ें",
        "consultation_summary": "परामर्श सारांश",
        "proceed_payment": "भुगतान के लिए आगे बढ़ें",
        "payment": "भुगतान",
        "consultation_fee": "परामर्श शुल्क: ₹500",
        "confirm_payment": "भुगतान की पुष्टि करें",
        "name_error": "नाम: केवल अक्षर",
        "mobile_error": "मोबाइल: 10 अंक",
        "aadhaar_error": "आधार: 12 अंक",
        "fill_all_fields": "कृपया सभी फ़ील्ड भरें।",
        "scanning_face_id": "फेस आईडी स्कैन कर रहा है...",
        "recognizing_face": "चेहरा पहचान रहा है...",
        "face_recognized_success": "रोगी आईडी के लिए चेहरा पहचाना गया:",
        "face_recognition_failed": "चेहरा पहचान विफल रहा:",
        "face_recognition_error": "चेहरा पहचान सेवा से कनेक्ट करने में त्रुटि।",
        "scanning_fingerprint": "फिंगरप्रिंट स्कैन कर रहा है...",
        "invalid_patient_id": "अमान्य रोगी आईडी।",
        "measuring": "माप रहा है...",
        "vitals_captured": "ऊंचाई: 172 सेमी<br>वजन: 68 किग्रा<br>तापमान: 98.6°F<br>बीपी: 120/80 एमएमएचजी<br>हृदय गति: 72 बीपीएम<br>बीएमआई: 23.0",
        "connecting": "रिमोट डॉक्टर से कनेक्ट हो रहा है...",
        "consultation_complete": "परामर्श पूर्ण। नुस्खा उत्पन्न।",
        "summary_details": "<b>निदान:</b> उच्च रक्तचाप<br><b>नुस्खा:</b> एम्लोडिपाइन 5 मिलीग्राम प्रतिदिन<br><b>अनुवर्ती:</b> 1 महीना<br><b>सारांश ऐप पर भेजा गया।</b>",
        "processing_payment": "भुगतान संसाधित हो रहा है...",
        "payment_successful": "भुगतान सफल! रसीद ऐप पर भेजी गई।",
        "app_header": "स्मार्ट हेल्थ ऐप और कियोस्क",
        "app_footer": "© 2025 स्मार्ट हेल्थ ऐप और कियोस्क डेमो। HTML, CSS और JavaScript के साथ निर्मित।",
        "date_time": "दिनांक/समय",
        "no_appointment_finger": "फिंगरप्रिंट लॉगिन के लिए कोई सक्रिय अपॉइंटमेंट नहीं मिला।",
        "date_unavailable": "चयनित तिथि उपलब्ध नहीं है। कृपया कोई अन्य चुनें।",
        "face_registration": "चेहरा पंजीकरण",
        "face_register_prompt": "कृपया अपने चेहरे की एक स्पष्ट तस्वीर लें या अपलोड करें।",
        "capture_photo": "फोटो कैप्चर करें",
        "upload_photo_btn": "फोटो अपलोड करें",
        "register_face_btn": "चेहरा पंजीकृत करें",
        "back_to_registration": "पंजीकरण पर वापस",
        "webcam_error": "वेबकैम तक पहुंच अस्वीकृत या उपलब्ध नहीं है।",
        "photo_captured": "फोटो कैप्चर किया गया। चेहरा पंजीकृत करें पर क्लिक करें।",
        "no_video_stream": "फोटो कैप्चर करने के लिए कोई वीडियो स्ट्रीम उपलब्ध नहीं है।",
        "photo_uploaded": "फोटो अपलोड किया गया। चेहरा पंजीकृत करें पर क्लिक करें।",
        "capture_upload_first": "कृपया पहले एक फोटो कैप्चर या अपलोड करें।",
        "register_first_error": "कृपया पहले अपने मूल विवरण पंजीकृत करें।",
        "registering_face": "चेहरा पंजीकृत कर रहा है...",
        "face_registered_msg": "चेहरा सफलतापूर्वक पंजीकृत!",
        "face_registration_failed": "चेहरा पंजीकरण विफल रहा:",
        "network_error_face_reg": "चेहरा पंजीकरण के दौरान नेटवर्क त्रुटि या सर्वर अनुपलब्ध।",
        "scanning_face_sim": "चेहरा स्कैन कर रहा है...",
        "face_not_recognized_kiosk": "चेहरा पहचाना नहीं गया। कृपया पहले ऐप में पंजीकरण करें या रोगी आईडी का प्रयास करें।",
        "network_error_face_rec": "चेहरा पहचान के दौरान नेटवर्क त्रुटि या सर्वर अनुपलब्ध।"
    },
    "Tamil": {
        "name": "பெயர்",
        "mobile": "மொபைல் எண்",
        "aadhaar": "ஆதார் எண்",
        "doctor": "மருத்துவர்",
        "register": "பதிவு",
        "scan_face": "முகம் ஸ்கேன் செய்யவும்",
        "appointment": "நியமனம்",
        "submit": "சமர்ப்பிக்கவும்",
        "welcome_to_app": "ஸ்மார்ட் ஹெல்த்துக்கு வரவேற்கிறோம்",
        "app_description": "தடையற்ற சுகாதாரத்திற்கான உங்கள் டிஜிட்டல் நுழைவாயில்.<br>சந்திப்புகளைப் பதிவு செய்யுங்கள், கியோஸ்கில் செக்-இன் செய்யுங்கள், உங்கள் ஆரோக்கியத்தை எளிதாக நிர்வகிக்கவும்.",
        "get_started": "தொடங்கவும்",
        "choose_lang": "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
        "registration_login": "பதிவு / உள்நுழைவு",
        "abha_id": "ஆபா ஐடி (விருப்பத்தேர்வு)",
        "face_scan": "முக ஸ்கேன் (பதிவேற்றம்)",
        "consent_ehr": "அங்கீகரிக்கப்பட்ட நிபுணர்களுடன் எனது EHR ஐப் பகிர நான் சம்மதிக்கிறேன்.",
        "register_login_btn": "பதிவு / உள்நுழைவு",
        "face_registration_link": "முக பதிவுக்காக தொடரவும்",
        "book_appointment": "மருத்துவர் சந்திப்பை பதிவு செய்யவும்",
        "department": "துறை",
        "mode": "முறை",
        "date": "தேதி",
        "time": "நேரம்",
        "confirm_appointment": "சந்திப்பை உறுதிப்படுத்தவும்",
        "appointment_confirmed": "சந்திப்பு உறுதிப்படுத்தப்பட்டது",
        "token": "டோக்கன்",
        "proceed_sync": "தொடரவும்: கியோஸ்க்குடன் ஒத்திசைக்கவும்",
        "ready_to_visit_kiosk": "கியோஸ்க்கைப் பார்வையிடத் தயார்",
        "appointment_scheduled_msg_part1": "உங்கள் சந்திப்பு கியோஸ்கில் திட்டமிடப்பட்டுள்ளது",
        "appointment_scheduled_msg_part2": "தயவுசெய்து கியோஸ்கிற்குச் செல்லவும். உங்கள் நோயாளி ஐடி:",
        "done": "முடிந்தது",
        "welcome_to_kiosk": "கியோஸ்க்குக்கு வரவேற்கிறோம்",
        "your_health_reports": "உங்கள் சுகாதார அறிக்கைகள்",
        "latest_consultation": "சமீபத்திய ஆலோசனை:",
        "prescription_label": "மருந்துச் சீட்டு:",
        "vitals_label": "முக்கியமானவை: இரத்த அழுத்தம்",
        "bmi_label": ", பிஎம்ஐ",
        "download_pdf": "PDF ஐப் பதிவிறக்கவும்",
        "kiosk_choose_lang": "கியோஸ்க்: உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
        "kiosk_login": "கியோஸ்க் உள்நுழைவு",
        "face_id": "முக ஐடி",
        "fingerprint": "கைரேகை",
        "patient_id": "நோயாளி ஐடி",
        "enter_patient_id": "நோயாளி ஐடியை உள்ளிடவும்",
        "login_btn": "உள்நுழையவும்",
        "kiosk_appointment_found": "கியோஸ்க்: சந்திப்பு கண்டறியப்பட்டது",
        "patient_id_label": "நோயாளி ஐடி:",
        "confirm_proceed": "உறுதிப்படுத்தி தொடரவும்",
        "vitals_diagnostics": "முக்கியமானவை மற்றும் நோயறிதல்கள்",
        "auto_capture_vitals": "தானியங்கி முறையில் முக்கியமானவற்றைப் பதிவு செய்யவும்",
        "proceed_teleconsultation": "தொலை ஆலோசனைக்குத் தொடரவும்",
        "teleconsultation": "தொலை ஆலோசனை",
        "start_consultation": "ஆலோசனையைத் தொடங்கவும்",
        "proceed_summary": "சுருக்கத்திற்குத் தொடரவும்",
        "consultation_summary": "ஆலோசனை சுருக்கம்",
        "proceed_payment": "கட்டணத்திற்குத் தொடரவும்",
        "payment": "கட்டணம்",
        "consultation_fee": "ஆலோசனை கட்டணம்: ₹500",
        "confirm_payment": "கட்டணத்தை உறுதிப்படுத்தவும்",
        "name_error": "பெயர்: எழுத்துகள் மட்டுமே",
        "mobile_error": "மொபைல்: 10 இலக்கங்கள்",
        "aadhaar_error": "ஆதார்: 12 இலக்கங்கள்",
        "fill_all_fields": "அனைத்து புலங்களையும் நிரப்பவும்.",
        "scanning_face_id": "முக ஐடி ஸ்கேன் செய்கிறது...",
        "recognizing_face": "முகத்தை அடையாளம் காண்கிறது...",
        "face_recognized_success": "நோயாளி ஐடிக்கு முகம் அடையாளம் காணப்பட்டது:",
        "face_recognition_failed": "முக அடையாளம் தோல்வியடைந்தது:",
        "face_recognition_error": "முக அடையாள சேவைக்கு இணைப்பதில் பிழை.",
        "scanning_fingerprint": "கைரேகை ஸ்கேன் செய்கிறது...",
        "invalid_patient_id": "தவறான நோயாளி ஐடி.",
        "measuring": "அளவிடுகிறது...",
        "vitals_captured": "உயரம்: 172 செ.மீ<br>எடை: 68 கிலோ<br>வெப்பநிலை: 98.6°F<br>இரத்த அழுத்தம்: 120/80 mmHg<br>இதயத் துடிப்பு: 72 bpm<br>பிஎம்ஐ: 23.0",
        "connecting": "தொலைதூர மருத்துவருடன் இணைகிறது...",
        "consultation_complete": "ஆலோசனை முடிந்தது. மருந்துச் சீட்டு உருவாக்கப்பட்டது.",
        "summary_details": "<b>நோயறிதல்:</b> உயர் இரத்த அழுத்தம்<br><b>மருந்துச் சீட்டு:</b> ஆம்லோடிபைன் 5 மி.கி தினமும்<br><b>பின்தொடர்தல்:</b> 1 மாதம்<br><b>சுருக்கம் செயலிக்கு அனுப்பப்பட்டது.</b>",
        "processing_payment": "கட்டணம் செயலாக்கப்படுகிறது...",
        "payment_successful": "கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது! ரசீது செயலிக்கு அனுப்பப்பட்டது.",
        "app_header": "ஸ்மார்ட் ஹெல்த் ஆப் & கியோஸ்க்",
        "app_footer": "© 2025 ஸ்மார்ட் ஹெல்த் ஆப் & கியோஸ்க் டெமோ. HTML, CSS & JavaScript மூலம் உருவாக்கப்பட்டது.",
        "date_time": "தேதி/நேரம்",
        "no_appointment_finger": "கைரேகை உள்நுழைவுக்கு செயலில் உள்ள சந்திப்பு எதுவும் இல்லை.",
        "date_unavailable": "தேர்ந்தெடுக்கப்பட்ட தேதி கிடைக்கவில்லை. தயவுசெய்து வேறொன்றைத் தேர்ந்தெடுக்கவும்.",
        "face_registration": "முக பதிவு",
        "face_register_prompt": "தயவுசெய்து உங்கள் முகத்தின் தெளிவான புகைப்படத்தை எடுக்கவும் அல்லது பதிவேற்றவும்.",
        "capture_photo": "புகைப்படம் எடுக்கவும்",
        "upload_photo_btn": "புகைப்படத்தை பதிவேற்றவும்",
        "register_face_btn": "முகத்தை பதிவு செய்யவும்",
        "back_to_registration": "பதிவுக்குத் திரும்பு",
        "webcam_error": "வெப்கேம் அணுகல் மறுக்கப்பட்டது அல்லது கிடைக்கவில்லை.",
        "photo_captured": "புகைப்படம் எடுக்கப்பட்டது. முகத்தை பதிவு செய்யவும் என்பதைக் கிளிக் செய்யவும்.",
        "no_video_stream": "புகைப்படம் எடுக்க வீடியோ ஸ்ட்ரீம் கிடைக்கவில்லை.",
        "photo_uploaded": "புகைப்படம் பதிவேற்றப்பட்டது. முகத்தை பதிவு செய்யவும் என்பதைக் கிளிக் செய்யவும்.",
        "capture_upload_first": "தயவுசெய்து முதலில் ஒரு புகைப்படத்தை எடுக்கவும் அல்லது பதிவேற்றவும்.",
        "register_first_error": "தயவுசெய்து உங்கள் அடிப்படை விவரங்களை முதலில் பதிவு செய்யவும்.",
        "registering_face": "முகத்தை பதிவு செய்கிறது...",
        "face_registered_msg": "முகம் வெற்றிகரமாக பதிவு செய்யப்பட்டது!",
        "face_registration_failed": "முக பதிவு தோல்வியடைந்தது:",
        "network_error_face_reg": "முக பதிவு செய்யும் போது பிணைய பிழை அல்லது சேவையகம் கிடைக்கவில்லை.",
        "scanning_face_sim": "முகத்தை ஸ்கேன் செய்கிறது...",
        "face_not_recognized_kiosk": "முகம் அடையாளம் காணப்படவில்லை. தயவுசெய்து முதலில் பயன்பாட்டில் பதிவு செய்யவும் அல்லது நோயாளி ஐடியை முயற்சிக்கவும்.",
        "network_error_face_rec": "முக அடையாளம் காணும் போது பிணைய பிழை அல்லது சேவையகம் கிடைக்கவில்லை."
    },
    "Bengali": {
        "name": "নাম",
        "mobile": "মোবাইল নম্বর",
        "aadhaar": "আধার নম্বর",
        "doctor": "ডাক্তার",
        "register": "নিবন্ধন",
        "scan_face": "মুখ স্ক্যান করুন",
        "appointment": "নিয়োগ",
        "submit": "জমা দিন",
        "welcome_to_app": "স্মার্ট হেলথে স্বাগতম",
        "app_description": "সহজ স্বাস্থ্যসেবার জন্য আপনার ডিজিটাল গেটওয়ে।<br>অ্যাপয়েন্টমেন্ট বুক করুন, কিয়স্কে চেক-ইন করুন এবং আপনার স্বাস্থ্য সহজে পরিচালনা করুন।",
        "get_started": "শুরু করুন",
        "choose_lang": "আপনার ভাষা নির্বাচন করুন",
        "registration_login": "নিবন্ধন / লগইন",
        "abha_id": "আভা আইডি (ঐচ্ছিক)",
        "face_scan": "মুখ স্ক্যান (আপলোড)",
        "consent_ehr": "আমি অনুমোদিত পেশাদারদের সাথে আমার EHR শেয়ার করতে সম্মতি দিচ্ছি।",
        "register_login_btn": "নিবন্ধন / লগইন",
        "face_registration_link": "মুখ নিবন্ধনের জন্য এগিয়ে যান",
        "book_appointment": "ডাক্তারের অ্যাপয়েন্টমেন্ট বুক করুন",
        "department": "বিভাগ",
        "mode": "মোড",
        "date": "তারিখ",
        "time": "সময়",
        "confirm_appointment": "অ্যাপয়েন্টমেন্ট নিশ্চিত করুন",
        "appointment_confirmed": "অ্যাপয়েন্টমেন্ট নিশ্চিত হয়েছে",
        "token": "টোকেন",
        "proceed_sync": "এগিয়ে যান: কিয়স্কের সাথে সিঙ্ক করুন",
        "ready_to_visit_kiosk": "কিয়স্ক পরিদর্শনে প্রস্তুত",
        "appointment_scheduled_msg_part1": "আপনার অ্যাপয়েন্টমেন্ট কিয়স্কে নির্ধারিত হয়েছে",
        "appointment_scheduled_msg_part2": "অনুগ্রহ করে কিয়স্কে যান। আপনার রোগীর আইডি:",
        "done": "হয়ে গেছে",
        "welcome_to_kiosk": "কিয়স্কে স্বাগতম",
        "your_health_reports": "আপনার স্বাস্থ্য রিপোর্ট",
        "latest_consultation": "সর্বশেষ পরামর্শ:",
        "prescription_label": "প্রেসক্রিপশন:",
        "vitals_label": "গুরুত্বপূর্ণ: বিপি",
        "bmi_label": ", বিএমআই",
        "download_pdf": "পিডিএফ ডাউনলোড করুন",
        "kiosk_choose_lang": "কিয়স্ক: আপনার ভাষা নির্বাচন করুন",
        "kiosk_login": "কিয়স্ক লগইন",
        "face_id": "ফেস আইডি",
        "fingerprint": "ফিঙ্গারপ্রিন্ট",
        "patient_id": "রোগী আইডি",
        "enter_patient_id": "রোগী আইডি লিখুন",
        "login_btn": "লগইন করুন",
        "kiosk_appointment_found": "কিয়স্ক: অ্যাপয়েন্টমেন্ট পাওয়া গেছে",
        "patient_id_label": "রোগী আইডি:",
        "confirm_proceed": "নিশ্চিত করুন এবং এগিয়ে যান",
        "vitals_diagnostics": "গুরুত্বপূর্ণ এবং রোগ নির্ণয়",
        "auto_capture_vitals": "স্বয়ংক্রিয়ভাবে গুরুত্বপূর্ণ ডেটা ক্যাপচার করুন",
        "proceed_teleconsultation": "টেলিকনসালটেশনে এগিয়ে যান",
        "teleconsultation": "টেলিকনসালটেশন",
        "start_consultation": "পরামর্শ শুরু করুন",
        "proceed_summary": "সারসংক্ষেপে এগিয়ে যান",
        "consultation_summary": "পরামর্শ সারসংক্ষেপ",
        "proceed_payment": "পেমেন্টের জন্য এগিয়ে যান",
        "payment": "পেমেন্ট",
        "consultation_fee": "পরামর্শ ফি: ₹৫০০",
        "confirm_payment": "পেমেন্ট নিশ্চিত করুন",
        "name_error": "নাম: শুধুমাত্র অক্ষর",
        "mobile_error": "মোবাইল: 10 সংখ্যা",
        "aadhaar_error": "আধার: 12 সংখ্যা",
        "fill_all_fields": "অনুগ্রহ করে সমস্ত ক্ষেত্র পূরণ করুন।",
        "scanning_face_id": "ফেস আইডি স্ক্যান হচ্ছে...",
        "recognizing_face": "চেহারা সনাক্ত করছে...",
        "face_recognized_success": "রোগীর আইডি জন্য মুখ সনাক্ত করা হয়েছে:",
        "face_recognition_failed": "মুখ সনাক্তকরণ ব্যর্থ হয়েছে:",
        "face_recognition_error": "মুখ সনাক্তকরণ পরিষেবাতে সংযোগ করতে ত্রুটি।",
        "scanning_fingerprint": "ফিঙ্গারপ্রিন্ট স্ক্যান হচ্ছে...",
        "invalid_patient_id": "অবৈধ রোগীর আইডি।",
        "measuring": "পরিমাপ হচ্ছে...",
        "vitals_captured": "উচ্চতা: ১৭২ সেমি<br>ওজন: ৬৮ কেজি<br>তাপমাত্রা: ৯৮.৬°F<br>বিপি: ১২০/৮০ mmHg<br>হার্ট রেট: ৭২ bpm<br>বিএমআই: ২৩.০",
        "connecting": "রিমোট ডাক্তারের সাথে সংযোগ হচ্ছে...",
        "consultation_complete": "পরামর্শ সম্পূর্ণ। প্রেসক্রিপশন তৈরি হয়েছে।",
        "summary_details": "<b>রোগ নির্ণয়:</b> উচ্চ রক্তচাপ<br><b>প্রেসক্রিপশন:</b> অ্যামলোডিপাইন 5 মিলিগ্রাম দৈনিক<br><b>ফলো-আপ:</b> 1 মাস<br><b>সারসংক্ষেপ অ্যাপে পাঠানো হয়েছে।</b>",
        "processing_payment": "পেমেন্ট প্রক্রিয়া করা হচ্ছে...",
        "payment_successful": "পেমেন্ট সফল! রশিদ অ্যাপে পাঠানো হয়েছে।",
        "app_header": "স্মার্ট হেলথ অ্যাপ ও কিয়স্ক",
        "app_footer": "© 2025 স্মার্ট হেলথ অ্যাপ ও কিয়স্ক ডেমো। HTML, CSS ও JavaScript দিয়ে নির্মিত।",
        "date_time": "তারিখ/সময়",
        "no_appointment_finger": "ফিংগারপ্রিন্ট লগইনের জন্য কোনো সক্রিয় অ্যাপয়েন্টমেন্ট পাওয়া যায়নি।",
        "date_unavailable": "নির্বাচিত তারিখ উপলব্ধ নেই। অনুগ্রহ করে অন্য একটি নির্বাচন করুন।",
        "face_registration": "মুখ নিবন্ধন",
        "face_register_prompt": "আপনার মুখের একটি স্পষ্ট ছবি তুলুন বা আপলোড করুন।",
        "capture_photo": "ছবি তুলুন",
        "upload_photo_btn": "ছবি আপলোড করুন",
        "register_face_btn": "মুখ নিবন্ধন করুন",
        "back_to_registration": "নিবন্ধনে ফিরে যান",
        "webcam_error": "ওয়েবক্যাম অ্যাক্সেস অস্বীকৃত বা উপলব্ধ নেই।",
        "photo_captured": "ছবি তোলা হয়েছে। মুখ নিবন্ধন করুন ক্লিক করুন।",
        "no_video_stream": "ছবি তোলার জন্য কোনো ভিডিও স্ট্রিম উপলব্ধ নেই।",
        "photo_uploaded": "ছবি আপলোড করা হয়েছে। মুখ নিবন্ধন করুন ক্লিক করুন।",
        "capture_upload_first": "অনুগ্রহ করে প্রথমে একটি ছবি তুলুন বা আপলোড করুন।",
        "register_first_error": "অনুগ্রহ করে প্রথমে আপনার মৌলিক বিবরণ নিবন্ধন করুন।",
        "registering_face": "মুখ নিবন্ধন করা হচ্ছে...",
        "face_registered_msg": "মুখ সফলভাবে নিবন্ধিত হয়েছে!",
        "face_registration_failed": "মুখ নিবন্ধন ব্যর্থ হয়েছে:",
        "network_error_face_reg": "মুখ নিবন্ধনের সময় নেটওয়ার্ক ত্রুটি বা সার্ভার অনুপলব্ধ।",
        "scanning_face_sim": "মুখ স্ক্যান হচ্ছে...",
        "face_not_recognized_kiosk": "মুখ সনাক্ত করা যায়নি। অনুগ্রহ করে প্রথমে অ্যাপে নিবন্ধন করুন অথবা রোগীর আইডি ব্যবহার করে চেষ্টা করুন।",
        "network_error_face_rec": "মুখ সনাক্তকরণের সময় নেটওয়ার্ক ত্রুটি বা সার্ভার অনুপলব্ধ।"
    },
    "Marathi": {
        "name": "नाव",
        "mobile": "मोबाईल नंबर",
        "aadhaar": "आधार क्रमांक",
        "doctor": "डॉक्टर",
        "register": "नोंदणी",
        "scan_face": "चेहरा स्कॅन करा",
        "appointment": "नियुक्ती",
        "submit": "सबमिट करा",
        "welcome_to_app": "स्मार्ट हेल्थमध्ये आपले स्वागत आहे",
        "app_description": "अखंड आरोग्यसेवेसाठी तुमचे डिजिटल प्रवेशद्वार.<br>भेटी बुक करा, कियोस्कवर चेक-इन करा आणि तुमचे आरोग्य सहज व्यवस्थापित करा.",
        "get_started": "प्रारंभ करा",
        "choose_lang": "तुमची भाषा निवडा",
        "registration_login": "नोंदणी / लॉगिन",
        "abha_id": "ABHA ID (पर्यायी)",
        "face_scan": "चेहरा स्कॅन (अपलोड)",
        "consent_ehr": "मी अधिकृत व्यावसायिकांसोबत माझा EHR सामायिक करण्यास संमती देतो.",
        "register_login_btn": "नोंदणी / लॉगिन",
        "face_registration_link": "चेहरा नोंदणीसाठी पुढे चला",
        "book_appointment": "डॉक्टरांच्या भेटीची नोंदणी करा",
        "department": "विभाग",
        "mode": "मोड",
        "date": "तारीख",
        "time": "वेळ",
        "confirm_appointment": "भेटीची पुष्टी करा",
        "appointment_confirmed": "भेटीची पुष्टी झाली",
        "token": "टोकन",
        "proceed_sync": "पुढे चला: कियोस्कसह समक्रमित करा",
        "ready_to_visit_kiosk": "कियोस्कला भेट देण्यासाठी सज्ज",
        "appointment_scheduled_msg_part1": "तुमची भेट कियोस्कवर नियोजित आहे",
        "appointment_scheduled_msg_part2": "कृपया कियोस्कवर जा. तुमचा रुग्ण आयडी:",
        "done": "पूर्ण झाले",
        "welcome_to_kiosk": "कियोस्कमध्ये आपले स्वागत आहे",
        "your_health_reports": "तुमचे आरोग्य अहवाल",
        "latest_consultation": "नवीनतम सल्लामसलत:",
        "prescription_label": "प्रिस्क्रिप्शन:",
        "vitals_label": "महत्वाची चिन्हे: बीपी",
        "bmi_label": ", बीएमआय",
        "download_pdf": "पीडीएफ डाउनलोड करा",
        "kiosk_choose_lang": "कियोस्क: तुमची भाषा निवडा",
        "kiosk_login": "कियोस्क लॉगिन",
        "face_id": "फेस आयडी",
        "fingerprint": "फिंगरप्रिंट",
        "patient_id": "रुग्ण आयडी",
        "enter_patient_id": "रुग्ण आयडी प्रविष्ट करा",
        "login_btn": "लॉगिन करा",
        "kiosk_appointment_found": "कियोस्क: भेट आढळली",
        "patient_id_label": "रुग्ण आयडी:",
        "confirm_proceed": "पुष्टी करा आणि पुढे चला",
        "vitals_diagnostics": "महत्वाची चिन्हे आणि निदान",
        "auto_capture_vitals": "स्वयं-कॅप्चर महत्वाची चिन्हे",
        "proceed_teleconsultation": "टेलीकंसल्टेशनसाठी पुढे चला",
        "teleconsultation": "टेलीकंसल्टेशन",
        "start_consultation": "सल्लामसलत सुरू करा",
        "proceed_summary": "सारांशासाठी पुढे चला",
        "consultation_summary": "सल्लामसलत सारांश",
        "proceed_payment": "पेमेंटसाठी पुढे चला",
        "payment": "पेमेंट",
        "consultation_fee": "सल्लामसलत शुल्क: ₹५००",
        "confirm_payment": "पेमेंटची पुष्टी करा",
        "name_error": "नाव: फक्त अक्षरे",
        "mobile_error": "मोबाइल: 10 अंक",
        "aadhaar_error": "आधार: 12 अंक",
        "fill_all_fields": "कृपया सर्व फील्ड भरा.",
        "scanning_face_id": "फेस आयडी स्कॅन करत आहे...",
        "recognizing_face": "चेहरा ओळखत आहे...",
        "face_recognized_success": "रुग्ण आयडी साठी चेहरा ओळखला गेला:",
        "face_recognition_failed": "चेहरा ओळखणे अयशस्वी झाले:",
        "face_recognition_error": "चेहरा ओळख सेवा जोडण्यात त्रुटी.",
        "scanning_fingerprint": "फिंगरप्रिंट स्कॅन करत आहे...",
        "invalid_patient_id": "अवैध रुग्ण आयडी.",
        "measuring": "मापन करत आहे...",
        "vitals_captured": "उंची: 172 सेमी<br>वजन: 68 किलो<br>तापमान: 98.6°F<br>बीपी: 120/80 mmHg<br>हृदय गती: 72 bpm<br>बीएमआय: 23.0",
        "connecting": "दूरस्थ डॉक्टरांशी कनेक्ट होत आहे...",
        "consultation_complete": "सल्लामसलत पूर्ण झाली. प्रिस्क्रिप्शन तयार.",
        "summary_details": "<b>निदान:</b> उच्च रक्तदाब<br><b>प्रिस्क्रिप्शन:</b> अम्लोडिपाइन 5 मिलीग्राम दररोज<br><b>फॉलो-अप:</b> 1 महिना<br><b>सारांश ॲपला पाठवला.</b>",
        "processing_payment": "पेमेंट प्रक्रिया करत आहे...",
        "payment_successful": "पेमेंट यशस्वी! पावती ॲपला पाठवली.",
        "app_header": "स्मार्ट हेल्थ ॲप आणि कियोस्क",
        "app_footer": "© 2025 स्मार्ट हेल्थ ॲप आणि कियोस्क डेमो. HTML, CSS आणि JavaScript वापरून तयार केले आहे.",
        "date_time": "तारीख/वेळ",
        "no_appointment_finger": "फिंगरप्रिंट लॉगिनसाठी कोणतीही सक्रिय अपॉइंटमेंट सापडली नाही.",
        "date_unavailable": "निवडलेली तारीख उपलब्ध नाही. कृपया दुसरी निवडा.",
        "face_registration": "चेहरा नोंदणी",
        "face_register_prompt": "कृपया आपल्या चेहऱ्याचा स्पष्ट फोटो घ्या किंवा अपलोड करा.",
        "capture_photo": "फोटो कॅप्चर करा",
        "upload_photo_btn": "फोटो अपलोड करा",
        "register_face_btn": "चेहरा नोंदणी करा",
        "back_to_registration": "नोंदणीवर परत जा",
        "webcam_error": "वेबकॅम प्रवेश नाकारला किंवा उपलब्ध नाही.",
        "photo_captured": "फोटो कॅप्चर केला. चेहरा नोंदणी करा क्लिक करा.",
        "no_video_stream": "फोटो कॅप्चर करण्यासाठी व्हिडिओ स्ट्रीम उपलब्ध नाही.",
        "photo_uploaded": "फोटो अपलोड केला. चेहरा नोंदणी करा क्लिक करा.",
        "capture_upload_first": "कृपया आधी एक फोटो कॅप्चर करा किंवा अपलोड करा.",
        "register_first_error": "कृपया आधी आपले मूलभूत तपशील नोंदणी करा.",
        "registering_face": "चेहरा नोंदणी करत आहे...",
        "face_registered_msg": "चेहरा यशस्वीरित्या नोंदणीकृत!",
        "face_registration_failed": "चेहरा नोंदणी अयशस्वी झाली:",
        "network_error_face_reg": "चेहरा नोंदणी करताना नेटवर्क त्रुटी किंवा सर्वर अनुपलब्ध.",
        "scanning_face_sim": "चेहरा स्कॅन करत आहे...",
        "face_not_recognized_kiosk": "चेहरा ओळखला नाही. कृपया आधी ॲपमध्ये नोंदणी करा किंवा रुग्ण आयडी वापरून पहा.",
        "network_error_face_rec": "चेहरा ओळखताना नेटवर्क त्रुटी किंवा सर्वर अनुपलब्ध."
    },
    "Telugu": {
        "name": "పేరు",
        "mobile": "మొబైల్ నంబర్",
        "aadhaar": "ఆధార్ నంబర్",
        "doctor": "డాక్టర్",
        "register": "నమోదు",
        "scan_face": "ముఖాన్ని స్కాన్ చేయండి",
        "appointment": "నియామకం",
        "submit": "సమర్పించండి",
        "welcome_to_app": "స్మార్ట్ హెల్త్‌కు స్వాగతం",
        "app_description": "నిరంతరాయ ఆరోగ్య సంరక్షణ కోసం మీ డిజిటల్ గేట్‌వే.<br>అపాయింట్‌మెంట్‌లను బుక్ చేయండి, కియోస్క్‌లలో చెక్-ఇన్ చేయండి మరియు మీ ఆరోగ్యాన్ని సులభంగా నిర్వహించండి.",
        "get_started": "ప్రారంభించండి",
        "choose_lang": "మీ భాషను ఎంచుకోండి",
        "registration_login": "నమోదు / లాగిన్",
        "abha_id": "అభ ID (ఐచ్ఛికం)",
        "face_scan": "ముఖం స్కాన్ (అప్‌లోడ్)",
        "consent_ehr": "అధికారిక నిపుణులతో నా EHRని పంచుకోవడానికి నేను సమ్మతిస్తున్నాను.",
        "register_login_btn": "నమోదు / లాగిన్",
        "face_registration_link": "ముఖ నమోదు కోసం కొనసాగండి",
        "book_appointment": "డాక్టర్ అపాయింట్‌మెంట్ బుక్ చేయండి",
        "department": "విభాగం",
        "mode": "మోడ్",
        "date": "తేదీ",
        "time": "సమయం",
        "confirm_appointment": "అపాయింట్‌మెంట్‌ను నిర్ధారించండి",
        "appointment_confirmed": "అపాయింట్‌మెంట్ నిర్ధారించబడింది",
        "token": "టోకెన్",
        "proceed_sync": "కొనసాగండి: కియోస్క్‌తో సమకాలీకరించండి",
        "ready_to_visit_kiosk": "కియోస్క్‌ను సందర్శించడానికి సిద్ధంగా ఉంది",
        "appointment_scheduled_msg_part1": "మీ అపాయింట్‌మెంట్ కియోస్క్‌లో షెడ్యూల్ చేయబడింది",
        "appointment_scheduled_msg_part2": "దయచేసి కియోస్క్‌కు వెళ్ళండి. మీ పేషెంట్ ID:",
        "done": "పూర్తయింది",
        "welcome_to_kiosk": "కియోస్క్‌కు స్వాగతం",
        "your_health_reports": "మీ ఆరోగ్య నివేదికలు",
        "latest_consultation": "తాజా సంప్రదింపు:",
        "prescription_label": "ప్రిస్క్రిప్షన్:",
        "vitals_label": "వైటల్స్: బిపి",
        "bmi_label": ", BMI",
        "download_pdf": "PDF డౌన్‌లోడ్ చేయండి",
        "kiosk_choose_lang": "కియోస్క్: మీ భాషను ఎంచుకోండి",
        "kiosk_login": "కియోస్క్ లాగిన్",
        "face_id": "ఫేస్ ID",
        "fingerprint": "ఫింగర్‌ప్రింట్",
        "patient_id": "పేషెంట్ ID",
        "enter_patient_id": "పేషెంట్ ID నమోదు చేయండి",
        "login_btn": "లాగిన్ చేయండి",
        "kiosk_appointment_found": "కియోస్క్: అపాయింట్‌మెంట్ కనుగొనబడింది",
        "patient_id_label": "పేషెంట్ ID:",
        "confirm_proceed": "నిర్ధారించి కొనసాగండి",
        "vitals_diagnostics": "వైటల్స్ మరియు డయాగ్నోస్టిక్స్",
        "auto_capture_vitals": "ఆటో-క్యాప్చర్ వైటల్స్",
        "proceed_teleconsultation": "టెలికన్సల్టేషన్ కోసం కొనసాగండి",
        "teleconsultation": "టెలికన్సల్టేషన్",
        "start_consultation": "సంప్రదింపు ప్రారంభించండి",
        "proceed_summary": "సారాంశం కోసం కొనసాగండి",
        "consultation_summary": "సంప్రదింపు సారాంశం",
        "proceed_payment": "చెల్లింపు కోసం కొనసాగండి",
        "payment": "చెల్లింపు",
        "consultation_fee": "సంప్రదింపు రుసుము: ₹500",
        "confirm_payment": "చెల్లింపును నిర్ధారించండి",
        "name_error": "పేరు: అక్షరాలు మాత్రమే",
        "mobile_error": "మొబైల్: 10 అంకెలు",
        "aadhaar_error": "ఆధార్: 12 అంకెలు",
        "fill_all_fields": "దయచేసి అన్ని ఫీల్డ్‌లను పూరించండి.",
        "scanning_face_id": "ఫేస్ ID స్కాన్ చేస్తోంది...",
        "recognizing_face": "ముఖాన్ని గుర్తిస్తోంది...",
        "face_recognized_success": "పేషెంట్ ID కోసం ముఖం గుర్తించబడింది:",
        "face_recognition_failed": "ముఖ గుర్తింపు విఫలమైంది:",
        "face_recognition_error": "ముఖ గుర్తింపు సేవకు కనెక్ట్ చేయడంలో లోపం.",
        "scanning_fingerprint": "ఫింగర్‌ప్రింట్ స్కాన్ చేస్తోంది...",
        "invalid_patient_id": "చెల్లని పేషెంట్ ID.",
        "measuring": "కొలుస్తోంది...",
        "vitals_captured": "ఎత్తు: 172 సెం.మీ<br>బరువు: 68 కిలోలు<br>ఉష్ణోగ్రత: 98.6°F<br>BP: 120/80 mmHg<br>గుండె రేటు: 72 bpm<br>BMI: 23.0",
        "connecting": "రిమోట్ డాక్టర్‌కి కనెక్ట్ అవుతోంది...",
        "consultation_complete": "సంప్రదింపు పూర్తయింది. ప్రిస్క్రిప్షన్ రూపొందించబడింది.",
        "summary_details": "<b>నిర్ధారణ:</b> రక్తపోటు<br><b>ప్రిస్క్రిప్షన్:</b> అమ్లోడిపైన్ 5mg రోజువారీ<br><b>తదుపరి నిఘా:</b> 1 నెల<br><b>సారాంశం యాప్‌కి పంపబడింది.</b>",
        "processing_payment": "చెల్లింపు ప్రాసెస్ చేస్తోంది...",
        "payment_successful": "చెల్లింపు విజయవంతమైంది! రసీదు యాప్‌కి పంపబడింది.",
        "app_header": "స్మార్ట్ హెల్త్ యాప్ & కియోస్క్",
        "app_footer": "© 2025 స్మార్ట్ హెల్త్ యాప్ & కియోస్క్ డెమో. HTML, CSS & JavaScriptతో నిర్మించబడింది.",
        "date_time": "తేదీ/సమయం",
        "no_appointment_finger": "వేలిముద్ర లాగిన్‌కు ఎటువంటి సక్రియ అపాయింట్‌మెంట్ కనుగొనబడలేదు.",
        "date_unavailable": "ఎంచుకున్న తేదీ అందుబాటులో లేదు. దయచేసి మరొకటి ఎంచుకోండి.",
        "face_registration": "ముఖ నమోదు",
        "face_register_prompt": "దయచేసి మీ ముఖం యొక్క స్పష్టమైన ఫోటోను క్యాప్చర్ చేయండి లేదా అప్‌లోడ్ చేయండి.",
        "capture_photo": "ఫోటోను క్యాప్చర్ చేయండి",
        "upload_photo_btn": "ఫోటోను అప్‌లోడ్ చేయండి",
        "register_face_btn": "ముఖాన్ని నమోదు చేయండి",
        "back_to_registration": "నమోదుకు తిరిగి వెళ్ళండి",
        "webcam_error": "వెబ్‌క్యామ్ యాక్సెస్ నిరాకరించబడింది లేదా అందుబాటులో లేదు.",
        "photo_captured": "ఫోటో క్యాప్చర్ చేయబడింది. ముఖాన్ని నమోదు చేయండి క్లిక్ చేయండి.",
        "no_video_stream": "ఫోటోను క్యాప్చర్ చేయడానికి వీడియో స్ట్రీమ్ అందుబాటులో లేదు.",
        "photo_uploaded": "ఫోటో అప్‌లోడ్ చేయబడింది. ముఖాన్ని నమోదు చేయండి క్లిక్ చేయండి.",
        "capture_upload_first": "దయచేసి ముందుగా ఒక ఫోటోను క్యాప్చర్ చేయండి లేదా అప్‌లోడ్ చేయండి.",
        "register_first_error": "దయచేసి ముందుగా మీ ప్రాథమిక వివరాలను నమోదు చేయండి.",
        "registering_face": "ముఖాన్ని నమోదు చేస్తోంది...",
        "face_registered_msg": "ముఖం విజయవంతంగా నమోదు చేయబడింది!",
        "face_registration_failed": "ముఖ నమోదు విఫలమైంది:",
        "network_error_face_reg": "ముఖ నమోదు సమయంలో నెట్‌వర్క్ లోపం లేదా సర్వర్ అందుబాటులో లేదు.",
        "scanning_face_sim": "ముఖాన్ని స్కాన్ చేస్తోంది...",
        "face_not_recognized_kiosk": "ముఖం గుర్తించబడలేదు. దయచేసి ముందుగా యాప్‌లో నమోదు చేసుకోండి లేదా పేషెంట్ ఐడిని ప్రయత్నించండి.",
        "network_error_face_rec": "ముఖ గుర్తింపు సమయంలో నెట్‌వర్క్ లోపం లేదా సర్వర్ అందుబాటులో లేదు."
    },
    "Kannada": {
        "name": "ಹೆಸರು",
        "mobile": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
        "aadhaar": "ಆಧಾರ್ ಸಂಖ್ಯೆ",
        "doctor": "ವೈದ್ಯರು",
        "register": "ನೋಂದಣಿ",
        "scan_face": "ಮುಖವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        "appointment": "ನೇಮಕಾತಿ",
        "submit": "ಸಲ್ಲಿಸಿ",
        "welcome_to_app": "ಸ್ಮಾರ್ಟ್ ಹೆಲ್ತ್‌ಗೆ ಸುಸ್ವಾಗತ",
        "app_description": "ತಡೆರಹಿತ ಆರೋಗ್ಯ ಸೇವೆಗಾಗಿ ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಹೆಬ್ಬಾಗಿಲು.<br>ನೇಮಕಾತಿಗಳನ್ನು ಕಾಯ್ದಿರಿಸಿ, ಕಿಯೋಸ್ಕ್‌ಗಳಲ್ಲಿ ಚೆಕ್-ಇನ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಆರೋಗ್ಯವನ್ನು ಸುಲಭವಾಗಿ ನಿರ್ವಹಿಸಿ.",
        "get_started": "ಪ್ರಾರಂಭಿಸಿ",
        "choose_lang": "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "registration_login": "ನೋಂದಣಿ / ಲಾಗಿನ್",
        "abha_id": "ABHA ID (ಐಚ್ಛಿಕ)",
        "face_scan": "ಮುಖ ಸ್ಕ್ಯಾನ್ (ಅಪ್‌ಲೋಡ್)",
        "consent_ehr": "ನಾನು ಅಧಿಕೃತ ವೃತ್ತಿಪರರೊಂದಿಗೆ ನನ್ನ EHR ಅನ್ನು ಹಂಚಿಕೊಳ್ಳಲು ಸಮ್ಮತಿಸುತ್ತೇನೆ.",
        "register_login_btn": "ನೋಂದಣಿ / ಲಾಗಿನ್",
        "face_registration_link": "ಮುಖ ನೋಂದಣಿಗೆ ಮುಂದುವರಿಯಿರಿ",
        "book_appointment": "ವೈದ್ಯರ ನೇಮಕಾತಿ ಪುಸ್ತಕ",
        "department": "ಇಲಾಖೆ",
        "mode": "ಮೋಡ್",
        "date": "ದಿನಾಂಕ",
        "time": "ಸಮಯ",
        "confirm_appointment": "ನೇಮಕಾತಿಯನ್ನು ದೃಢೀಕರಿಸಿ",
        "appointment_confirmed": "ನೇಮಕಾತಿ ದೃಢೀಕರಿಸಲಾಗಿದೆ",
        "token": "ಟೋಕನ್",
        "proceed_sync": "ಮುಂದುವರಿಸಿ: ಕಿಯೋಸ್ಕ್‌ನೊಂದಿಗೆ ಸಿಂಕ್ ಮಾಡಿ",
        "ready_to_visit_kiosk": "ಕಿಯೋಸ್ಕ್‌ಗೆ ಭೇಟಿ ನೀಡಲು ಸಿದ್ಧ",
        "appointment_scheduled_msg_part1": "ನಿಮ್ಮ ನೇಮಕಾತಿಯನ್ನು ಕಿಯೋಸ್ಕ್‌ನಲ್ಲಿ ನಿಗದಿಪಡಿಸಲಾಗಿದೆ",
        "appointment_scheduled_msg_part2": "ದಯವಿಟ್ಟು ಕಿಯೋಸ್ಕ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ. ನಿಮ್ಮ ರೋಗಿ ID:",
        "done": "ಮುಗಿದಿದೆ",
        "welcome_to_kiosk": "ಕಿಯೋಸ್ಕ್‌ಗೆ ಸುಸ್ವಾಗತ",
        "your_health_reports": "ನಿಮ್ಮ ಆರೋಗ್ಯ ವರದಿಗಳು",
        "latest_consultation": "ಇತ್ತೀಚಿನ ಸಮಾಲೋಚನೆ:",
        "prescription_label": "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್:",
        "vitals_label": "ಪ್ರಮುಖ ಚಿಹ್ನೆಗಳು: ಬಿಪಿ",
        "bmi_label": ", BMI",
        "download_pdf": "PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
        "kiosk_choose_lang": "ಕಿಯೋಸ್ಕ್: ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "kiosk_login": "ಕಿಯೋಸ್ಕ್ ಲಾಗಿನ್",
        "face_id": "ಮುಖ ID",
        "fingerprint": "ಬೆರಳಚ್ಚು",
        "patient_id": "ರೋಗಿ ID",
        "enter_patient_id": "ರೋಗಿ ID ನಮೂದಿಸಿ",
        "login_btn": "ಲಾಗಿನ್",
        "kiosk_appointment_found": "ಕಿಯೋಸ್ಕ್: ನೇಮಕಾತಿ ಕಂಡುಬಂದಿದೆ",
        "patient_id_label": "ರೋಗಿ ID:",
        "confirm_proceed": "ದೃಢೀಕರಿಸಿ ಮತ್ತು ಮುಂದುವರಿಸಿ",
        "vitals_diagnostics": "ಪ್ರಮುಖ ಚಿಹ್ನೆಗಳು ಮತ್ತು ರೋಗನಿರ್ಣಯ",
        "auto_capture_vitals": "ಸ್ವಯಂ-ಕ್ಯಾಪ್ಚರ್ ಪ್ರಮುಖ ಚಿಹ್ನೆಗಳು",
        "proceed_teleconsultation": "ದೂರಸಂಪರ್ಕ ಸಮಾಲೋಚನೆಗೆ ಮುಂದುವರಿಯಿರಿ",
        "teleconsultation": "ದೂರಸಂಪರ್ಕ ಸಮಾಲೋಚನೆ",
        "start_consultation": "ಸಮಾಲೋಚನೆ ಪ್ರಾರಂಭಿಸಿ",
        "proceed_summary": "ಸಾರಾಂಶಕ್ಕೆ ಮುಂದುವರಿಯಿರಿ",
        "consultation_summary": "ಸಮಾಲೋಚನೆ ಸಾರಾಂಶ",
        "proceed_payment": "ಪಾವತಿಗೆ ಮುಂದುವರಿಯಿರಿ",
        "payment": "ಪಾವತಿ",
        "consultation_fee": "ಸಮಾಲೋಚನೆ ಶುಲ್ಕ: ₹500",
        "confirm_payment": "ಪಾವತಿಯನ್ನು ದೃಢೀಕರಿಸಿ",
        "name_error": "ಹೆಸರು: ಅಕ್ಷರಗಳು ಮಾತ್ರ",
        "mobile_error": "ಮೊಬೈಲ್: 10 ಅಂಕೆಗಳು",
        "aadhaar_error": "ಆಧಾರ್: 12 ಅಂಕೆಗಳು",
        "fill_all_fields": "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
        "scanning_face_id": "ಮುಖ ID ಸ್ಕ್ಯಾನ್ ಆಗುತ್ತಿದೆ...",
        "recognizing_face": "ಮುಖವನ್ನು ಗುರುತಿಸಲಾಗುತ್ತಿದೆ...",
        "face_recognized_success": "ರೋಗಿ ID ಗಾಗಿ ಮುಖ ಗುರುತಿಸಲಾಗಿದೆ:",
        "face_recognition_failed": "ಮುಖ ಗುರುತಿಸುವಿಕೆ ವಿಫಲವಾಗಿದೆ:",
        "face_recognition_error": "ಮುಖ ಗುರುತಿಸುವಿಕೆ ಸೇವೆಗೆ ಸಂಪರ್ಕಿಸುವಲ್ಲಿ ದೋಷ.",
        "scanning_fingerprint": "ಬೆರಳಚ್ಚು ಸ್ಕ್ಯಾನ್ ಆಗುತ್ತಿದೆ...",
        "invalid_patient_id": "ಅಮಾನ್ಯ ರೋಗಿ ID.",
        "measuring": "ಅಳತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...",
        "vitals_captured": "ಎತ್ತರ: 172 ಸೆಂ.ಮೀ<br>ತೂಕ: 68 ಕೆಜಿ<br>ತಾಪಮಾನ: 98.6°F<br>ಬಿಪಿ: 120/80 mmHg<br>ಹೃದಯ ಬಡಿತ: 72 bpm<br>ಬಿಎಂಐ: 23.0",
        "connecting": "ರಿಮೋಟ್ ವೈದ್ಯರಿಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...",
        "consultation_complete": "ಸಮಾಲೋಚನೆ ಪೂರ್ಣಗೊಂಡಿದೆ. ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ರಚಿಸಲಾಗಿದೆ.",
        "summary_details": "<b>ರೋಗನಿರ್ಣಯ:</b> ಅಧಿಕ ರಕ್ತದೊತ್ತಡ<br><b>ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್:</b> ಅಮ್ಲೋಡಿಪೈನ್ 5mg ಪ್ರತಿದಿನ<br><b>ಫಾಲೋ-ಅಪ್:</b> 1 ತಿಂಗಳು<br><b>ಸಾರಾಂಶವನ್ನು ಅಪ್ಲಿಕೇಶನ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.</b>",
        "processing_payment": "ಪಾವತಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
        "payment_successful": "ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ! ರಸೀದಿಯನ್ನು ಅಪ್ಲಿಕೇಶನ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.",
        "app_header": "ಸ್ಮಾರ್ಟ್ ಹೆಲ್ತ್ ಆಪ್ & ಕಿಯೋಸ್ಕ್",
        "app_footer": "© 2025 ಸ್ಮಾರ್ಟ್ ಹೆಲ್ತ್ ಆಪ್ & ಕಿಯೋಸ್ಕ್ ಡೆಮೊ. HTML, CSS & JavaScript ಬಳಸಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.",
        "date_time": "ದಿನಾಂಕ/ಸಮಯ",
        "no_appointment_finger": "ಬೆರಳಚ್ಚು ಲಾಗಿನ್‌ಗಾಗಿ ಯಾವುದೇ ಸಕ್ರಿಯ ನೇಮಕಾತಿ ಕಂಡುಬಂದಿಲ್ಲ.",
        "date_unavailable": "ಆಯ್ಕೆ ಮಾಡಿದ ದಿನಾಂಕ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಬೇರೊಂದನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
        "face_registration": "ಮುಖ ನೋಂದಣಿ",
        "face_register_prompt": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಮುಖದ ಸ್ಪಷ್ಟ ಫೋಟೋವನ್ನು ಸೆರೆಹಿಡಿಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        "capture_photo": "ಫೋಟೋ ಸೆರೆಹಿಡಿಯಿರಿ",
        "upload_photo_btn": "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        "register_face_btn": "ಮುಖವನ್ನು ನೋಂದಾಯಿಸಿ",
        "back_to_registration": "ನೋಂದಣಿಗೆ ಹಿಂತಿರುಗಿ",
        "webcam_error": "ವೆಬ್‌ಕ್ಯಾಮ್ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ ಅಥವಾ ಲಭ್ಯವಿಲ್ಲ.",
        "photo_captured": "ಫೋಟೋ ಸೆರೆಹಿಡಿಯಲಾಗಿದೆ. ಮುಖವನ್ನು ನೋಂದಾಯಿಸಿ ಕ್ಲಿಕ್ ಮಾಡಿ.",
        "no_video_stream": "ಫೋಟೋ ಸೆರೆಹಿಡಿಯಲು ವೀಡಿಯೊ ಸ್ಟ್ರೀಮ್ ಲಭ್ಯವಿಲ್ಲ.",
        "photo_uploaded": "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ. ಮುಖವನ್ನು ನೋಂದಾಯಿಸಿ ಕ್ಲಿಕ್ ಮಾಡಿ.",
        "capture_upload_first": "ದಯವಿಟ್ಟು ಮೊದಲು ಒಂದು ಫೋಟೋವನ್ನು ಸೆರೆಹಿಡಿಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        "register_first_error": "ದಯವಿಟ್ಟು ಮೊದಲು ನಿಮ್ಮ ಮೂಲ ವಿವರಗಳನ್ನು ನೋಂದಾಯಿಸಿ.",
        "registering_face": "ಮುಖವನ್ನು ನೋಂದಾಯಿಸಲಾಗುತ್ತಿದೆ...",
        "face_registered_msg": "ಮುಖ ಯಶಸ್ವಿಯಾಗಿ ನೋಂದಾಯಿಸಲಾಗಿದೆ!",
        "face_registration_failed": "ಮುಖ ನೋಂದಣಿ ವಿಫಲವಾಗಿದೆ:",
        "network_error_face_reg": "ಮುಖ ನೋಂದಣಿಯ ಸಮಯದಲ್ಲಿ ನೆಟ್‌ವರ್ಕ್ ದೋಷ ಅಥವಾ ಸರ್ವರ್ ಲಭ್ಯವಿಲ್ಲ.",
        "scanning_face_sim": "ಮುಖ ಸ್ಕ್ಯಾನ್ ಆಗುತ್ತಿದೆ...",
        "face_not_recognized_kiosk": "ಮುಖ ಗುರುತಿಸಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೊದಲು ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ನೋಂದಾಯಿಸಿ ಅಥವಾ ರೋಗಿ ID ಯನ್ನು ಪ್ರಯತ್ನಿಸಿ.",
        "network_error_face_rec": "ಮುಖ ಗುರುತಿಸುವಿಕೆಯ ಸಮಯದಲ್ಲಿ ನೆಟ್‌ವರ್ಕ್ ದೋಷ ಅಥವಾ ಸರ್ವರ್ ಲಭ್ಯವಿಲ್ಲ."
    },
    "Malayalam": {
        "name": "പേര്",
        "mobile": "മൊബൈല്‍ നമ്പര്‍",
        "aadhaar": "ആധാര്‍ നമ്പര്‍",
        "doctor": "ഡോക്ടര്‍",
        "register": "രജിസ്റ്റർ ചെയ്യുക",
        "scan_face": "മുഖം സ്കാൻ ചെയ്യുക",
        "appointment": "നിയമനം",
        "submit": "സമർപ്പിക്കുക",
        "welcome_to_app": "സ്മാർട്ട് ഹെൽത്തിലേക്ക് സ്വാഗതം",
        "app_description": "തടസ്സങ്ങളില്ലാത്ത ആരോഗ്യ പരിചരണത്തിലേക്കുള്ള നിങ്ങളുടെ ഡിജിറ്റൽ കവാടം.<br>അപ്പോയിന്റ്‌മെന്റുകൾ ബുക്ക് ചെയ്യുക, കിയോസ്‌കുകളിൽ ചെക്ക്-ഇൻ ചെയ്യുക, നിങ്ങളുടെ ആരോഗ്യം എളുപ്പത്തിൽ കൈകാര്യം ചെയ്യുക.",
        "get_started": "തുടങ്ങുക",
        "choose_lang": "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
        "registration_login": "രജിസ്ട്രേഷൻ / ലോഗിൻ",
        "abha_id": "ആഭാ ഐഡി (ഓപ്ഷണൽ)",
        "face_scan": "മുഖം സ്കാൻ (അപ്‌ലോഡ്)",
        "consent_ehr": "അംഗീകൃത പ്രൊഫഷണലുകളുമായി എന്റെ EHR പങ്കിടാൻ ഞാൻ സമ്മതിക്കുന്നു.",
        "register_login_btn": "രജിസ്റ്റർ / ലോഗിൻ",
        "face_registration_link": "മുഖം രജിസ്ട്രേഷനിലേക്ക് തുടരുക",
        "book_appointment": "ഡോക്ടർ അപ്പോയിന്റ്‌മെന്റ് ബുക്ക് ചെയ്യുക",
        "department": "വകുപ്പ്",
        "mode": "മോഡ്",
        "date": "തീയതി",
        "time": "സമയം",
        "confirm_appointment": "അപ്പോയിന്റ്‌മെന്റ് സ്ഥിരീകരിക്കുക",
        "appointment_confirmed": "അപ്പോയിന്റ്‌മെന്റ് സ്ഥിരീകരിച്ചു",
        "token": "ടോക്കൺ",
        "proceed_sync": "തുടരുക: കിയോസ്‌കുമായി സമന്വയിപ്പിക്കുക",
        "ready_to_visit_kiosk": "കിയോസ്‌ക് സന്ദർശിക്കാൻ തയ്യാറാണ്",
        "appointment_scheduled_msg_part1": "നിങ്ങളുടെ അപ്പോയിന്റ്‌മെന്റ് കിയോസ്‌കിൽ ഷെഡ്യൂൾ ചെയ്തിരിക്കുന്നു",
        "appointment_scheduled_msg_part2": "ദയവായി കിയോസ്‌കിലേക്ക് പോകുക. നിങ്ങളുടെ പേഷ്യന്റ് ഐഡി:",
        "done": "ചെയ്തു",
        "welcome_to_kiosk": "കിയോസ്‌കിലേക്ക് സ്വാഗതം",
        "your_health_reports": "നിങ്ങളുടെ ആരോഗ്യ റിപ്പോർട്ടുകൾ",
        "latest_consultation": "ഏറ്റവും പുതിയ കൺസൾട്ടേഷൻ:",
        "prescription_label": "പ്രസ്‌ക്രിപ്‌ഷൻ:",
        "vitals_label": "വൈറ്റൽസ്: BP",
        "bmi_label": ", BMI",
        "download_pdf": "PDF ഡൗൺലോഡ് ചെയ്യുക",
        "kiosk_choose_lang": "കിയോസ്ക്: നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
        "kiosk_login": "കിയോസ്‌ക് ലോഗിൻ",
        "face_id": "ഫേസ് ഐഡി",
        "fingerprint": "ഫിംഗർപ്രിന്റ്",
        "patient_id": "രോഗി ഐഡി",
        "enter_patient_id": "രോഗി ഐഡി നൽകുക",
        "login_btn": "ലോഗിൻ",
        "kiosk_appointment_found": "കിയോസ്ക്: അപ്പോയിന്റ്‌മെന്റ് കണ്ടെത്തി",
        "patient_id_label": "രോഗി ഐഡി:",
        "confirm_proceed": "സ്ഥിരീകരിച്ച് തുടരുക",
        "vitals_diagnostics": "വൈറ്റൽസ് & ഡയഗ്നോസ്റ്റിക്സ്",
        "auto_capture_vitals": "ഓട്ടോ-ക്യാപ്ചർ വൈറ്റൽസ്",
        "proceed_teleconsultation": "ടെലികൺസൾട്ടേഷനിലേക്ക് പോകുക",
        "teleconsultation": "ടെലികൺസൾട്ടേഷൻ",
        "start_consultation": "കൺസൾട്ടേഷൻ ആരംഭിക്കുക",
        "proceed_summary": "സംഗ്രഹത്തിലേക്ക് പോകുക",
        "consultation_summary": "കൺസൾട്ടേഷൻ സംഗ്രഹം",
        "proceed_payment": "പെയ്‌മെന്റിലേക്ക് പോകുക",
        "payment": "പെയ്‌മെന്റ്",
        "consultation_fee": "കൺസൾട്ടേഷൻ ഫീസ്: ₹500",
        "confirm_payment": "പെയ്‌മെന്റ് സ്ഥിരീകരിക്കുക",
        "name_error": "പേര്: അക്ഷരങ്ങൾ മാത്രം",
        "mobile_error": "മൊബൈൽ: 10 അക്കങ്ങൾ",
        "aadhaar_error": "ആധാർ: 12 അക്കങ്ങൾ",
        "fill_all_fields": "എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക.",
        "scanning_face_id": "ഫേസ് ഐഡി സ്കാൻ ചെയ്യുന്നു...",
        "recognizing_face": "മുഖം തിരിച്ചറിയുന്നു...",
        "face_recognized_success": "രോഗി ഐഡിക്ക് മുഖം തിരിച്ചറിഞ്ഞു:",
        "face_recognition_failed": "മുഖം തിരിച്ചറിയൽ പരാജയപ്പെട്ടു:",
        "face_recognition_error": "മുഖം തിരിച്ചറിയൽ സേവനത്തിലേക്ക് കണക്റ്റുചെയ്യുന്നതിൽ പിശക്.",
        "scanning_fingerprint": "ഫിംഗർപ്രിന്റ് സ്കാൻ ചെയ്യുന്നു...",
        "invalid_patient_id": "അസാധുവായ രോഗി ഐഡി.",
        "measuring": "അളക്കുന്നു...",
        "vitals_captured": "ഉയരം: 172 സെ.മീ<br>ഭാരം: 68 കി.ഗ്രാം<br>താപനില: 98.6°F<br>BP: 120/80 mmHg<br>ഹൃദയമിടിപ്പ്: 72 bpm<br>BMI: 23.0",
        "connecting": "റിമോട്ട് ഡോക്ടറുമായി ബന്ധിപ്പിക്കുന്നു...",
        "consultation_complete": "കൺസൾട്ടേഷൻ പൂർത്തിയായി. പ്രസ്‌ക്രിപ്‌ഷൻ ജനറേറ്റ് ചെയ്തു.",
        "summary_details": "<b>രോഗനിർണയം:</b> രക്തസമ്മർദം<br><b>പ്രസ്‌ക്രിപ്‌ഷൻ:</b> അംലോഡിപൈൻ 5mg ദിവസവും<br><b>ഫോളോ-അപ്പ്:</b> 1 മാസം<br><b>സംഗ്രഹം ആപ്പിലേക്ക് അയച്ചു.</b>",
        "processing_payment": "പെയ്‌മെന്റ് പ്രോസസ്സ് ചെയ്യുന്നു...",
        "payment_successful": "പെയ്‌മെന്റ് വിജയകരം! രസീത് ആപ്പിലേക്ക് അയച്ചു.",
        "app_header": "സ്മാർട്ട് ഹെൽത്ത് ആപ്പ് & കിയോസ്ക്",
        "app_footer": "© 2025 സ്മാർട്ട് ഹെൽത്ത് ആപ്പ് & കിയോസ്ക് ഡെമോ. HTML, CSS & JavaScript ഉപയോഗിച്ച് നിർമ്മിച്ചത്.",
        "date_time": "തീയതി/സമയം",
        "no_appointment_finger": "വിരലടയാളം ഉപയോഗിച്ചുള്ള പ്രവേശനത്തിന് സജീവമായ നിയമനം കണ്ടെത്തിയില്ല.",
        "date_unavailable": "തിരഞ്ഞെടുത്ത തീയതി ലഭ്യമല്ല. ദയവായി മറ്റൊന്ന് തിരഞ്ഞെടുക്കുക.",
        "face_registration": "മുഖം രജിസ്ട്രേഷൻ",
        "face_register_prompt": "ദയവായി നിങ്ങളുടെ മുഖത്തിന്റെ വ്യക്തമായ ചിത്രം എടുക്കുക അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക.",
        "capture_photo": "ചിത്രം എടുക്കുക",
        "upload_photo_btn": "ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
        "register_face_btn": "മുഖം രജിസ്റ്റർ ചെയ്യുക",
        "back_to_registration": "രജിസ്ട്രേഷനിലേക്ക് തിരികെ",
        "webcam_error": "വെബ്‌ക്യാം ആക്സസ് നിഷേധിച്ചു അല്ലെങ്കിൽ ലഭ്യമല്ല.",
        "photo_captured": "ചിത്രം പകർത്തി. മുഖം രജിസ്റ്റർ ചെയ്യുക ക്ലിക്ക് ചെയ്യുക.",
        "no_video_stream": "ചിത്രം പകർത്താൻ വീഡിയോ സ്ട്രീം ലഭ്യമല്ല.",
        "photo_uploaded": "ചിത്രം അപ്‌ലോഡ് ചെയ്തു. മുഖം രജിസ്റ്റർ ചെയ്യുക ക്ലിക്ക് ചെയ്യുക.",
        "capture_upload_first": "ദയവായി ആദ്യം ഒരു ചിത്രം എടുക്കുക അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക.",
        "register_first_error": "ദയവായി ആദ്യം നിങ്ങളുടെ അടിസ്ഥാന വിവരങ്ങൾ രജിസ്റ്റർ ചെയ്യുക.",
        "registering_face": "മുഖം രജിസ്റ്റർ ചെയ്യുന്നു...",
        "face_registered_msg": "മുഖം വിജയകരമായി രജിസ്റ്റർ ചെയ്തു!",
        "face_registration_failed": "മുഖം രജിസ്ട്രേഷൻ പരാജയപ്പെട്ടു:",
        "network_error_face_reg": "മുഖം രജിസ്റ്റർ ചെയ്യുമ്പോൾ നെറ്റ്‌വർക്ക് പിശക് അല്ലെങ്കിൽ സെർവർ ലഭ്യമല്ല.",
        "scanning_face_sim": "മുഖം സ്കാൻ ചെയ്യുന്നു...",
        "face_not_recognized_kiosk": "മുഖം തിരിച്ചറിഞ്ഞില്ല. ദയവായി ആദ്യം ആപ്പിൽ രജിസ്റ്റർ ചെയ്യുക അല്ലെങ്കിൽ പേഷ്യന്റ് ഐഡി ഉപയോഗിച്ച് ശ്രമിക്കുക.",
        "network_error_face_rec": "മുഖം തിരിച്ചറിയുമ്പോൾ നെറ്റ്‌വർക്ക് പിശക് അല്ലെങ്കിൽ സെർവർ ലഭ്യമല്ല."
    }
}


@app.route('/labels', methods=['GET'])
def get_labels():
    lang = request.args.get('lang', 'English')
    return jsonify(LANGUAGES.get(lang, LANGUAGES['English']))

if __name__ == '__main__':
    # Run on host '0.0.0.0' to be accessible from other devices on the network.
    # debug=True allows for auto-reloading and better error messages during development.
    app.run(host='0.0.0.0', port=5001, debug=True)

